# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
    ]
