# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170224_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project_description',
            field=models.CharField(max_length=4096),
        ),
    ]
